/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BilledTokenCounts } from './billed-token-counts';
// May contain unused imports in some cases
// @ts-ignore
import type { BillingModelRef } from './billing-model-ref';
// May contain unused imports in some cases
// @ts-ignore
import type { ReasoningOutput } from './reasoning-output';
// May contain unused imports in some cases
// @ts-ignore
import type { StageContextWindowProjection } from './stage-context-window-projection';

/**
 * Properties for the `agent.message` event.
 */
export interface AgentMessageProps {
    'text': string;
    'model': BillingModelRef;
    'billing': BilledTokenCounts;
    'tool_call_count': number;
    'visit': number;
    'message'?: { [key: string]: any; } | null;
    'context_window'?: StageContextWindowProjection | null;
    'reasoning'?: ReasoningOutput | null;
}
