/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InterviewOption } from './interview-option';
// May contain unused imports in some cases
// @ts-ignore
import type { QuestionType } from './question-type';
// May contain unused imports in some cases
// @ts-ignore
import type { ReviewTarget } from './review-target';

/**
 * A pending human-in-the-loop question generated by a workflow stage.
 */
export interface ApiQuestion {
    /**
     * Unique question identifier.
     */
    'id': string;
    /**
     * The question text displayed to the user.
     */
    'text': string;
    /**
     * Workflow stage identifier that produced the question.
     */
    'stage': string;
    'question_type': QuestionType;
    /**
     * Available options for selection-based questions. Empty for freeform questions.
     */
    'options': Array<InterviewOption>;
    /**
     * Whether the user may provide freeform text in addition to selecting options.
     */
    'allow_freeform': boolean;
    /**
     * Timeout for the question when configured by the workflow.
     */
    'timeout_seconds'?: number | null;
    /**
     * Optional contextual text shown alongside the question.
     */
    'context_display'?: string | null;
    'review_target'?: ReviewTarget | null;
}
