/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Run IDs to delete as one bounded fail-soft batch.
 */
export interface BatchDeleteRunsRequest {
    /**
     * Run IDs to process, in result order.
     */
    'run_ids': Array<string>;
    /**
     * Whether to force deletion of active runs. Defaults to `false`.
     */
    'force'?: boolean;
}
