/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompletionMessage } from './completion-message';

/**
 * Body of POST /api/v1/playground/chat. The server is stateless across turns: the browser owns the draft and submits it as the literal `workflow.fabro` contents with every turn. The server embeds the file in the model\'s system prompt and exposes a single `write_workflow_file` tool that emits the full new contents of `workflow.fabro`; the browser parses, diffs, and animates the result.
 */
export interface CreatePlaygroundChatRequest {
    /**
     * assistant-ui-style message history for the turn.
     */
    'messages': Array<CompletionMessage>;
    /**
     * Full current `workflow.fabro` (Graphviz DOT) contents as rendered by the client — a complete `digraph <name> { ... }` block including the `start` / `exit` terminals. This is the same format the model writes back via `write_workflow_file`.
     */
    'workflow_fabro': string;
    /**
     * Model ID or alias. Server picks a ready-provider default if omitted.
     */
    'model'?: string;
    /**
     * Optional provider pin.
     */
    'provider'?: string;
}
