/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { McpTransport } from './mcp-transport';

/**
 * Request body for creating an MCP server definition.
 */
export interface CreateMcpServerRequest {
    /**
     * Stable MCP server identifier, used as the runtime MCP server name in qualified tool names.
     */
    'id': string;
    /**
     * Human-readable label for display in management UIs.
     */
    'display_name': string;
    'description'?: string | null;
    'transport': McpTransport;
    'startup_timeout_secs': number;
    'tool_timeout_secs': number;
}
