/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Reason attached to a failed terminal run status.
 */

export const FailureReason = {
    WORKFLOW_ERROR: 'workflow_error',
    PUBLISH_FAILED: 'publish_failed',
    CANCELLED: 'cancelled',
    APPROVAL_DENIED: 'approval_denied',
    TERMINATED: 'terminated',
    TRANSIENT_INFRA: 'transient_infra',
    BUDGET_EXHAUSTED: 'budget_exhausted',
    LAUNCH_FAILED: 'launch_failed',
    BOOTSTRAP_FAILED: 'bootstrap_failed',
    SANDBOX_INIT_FAILED: 'sandbox_init_failed'
} as const;

export type FailureReason = typeof FailureReason[keyof typeof FailureReason];
