/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InterviewOption } from './interview-option';
// May contain unused imports in some cases
// @ts-ignore
import type { QuestionType } from './question-type';
// May contain unused imports in some cases
// @ts-ignore
import type { ReviewTarget } from './review-target';

/**
 * Storage shape of an interview question recorded in the event log.
 */
export interface InterviewQuestionRecord {
    'id': string;
    'text': string;
    'stage': string;
    'question_type': QuestionType;
    'options'?: Array<InterviewOption>;
    'allow_freeform': boolean;
    'timeout_seconds'?: number | null;
    'context_display'?: string | null;
    'review_target'?: ReviewTarget | null;
}
