/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Kind of output a provider produced first for an inference attempt. Observed, never inferred.
 */

export const LlmOutputKind = {
    REASONING: 'reasoning',
    TEXT: 'text',
    TOOL_CALL: 'tool_call'
} as const;

export type LlmOutputKind = typeof LlmOutputKind[keyof typeof LlmOutputKind];
