/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Sparse command-local args that affect run settings.
 */
export interface ManifestArgs {
    'model'?: string;
    'provider'?: string;
    /**
     * Named environment slug to select for the run.
     */
    'environment'?: string;
    'verbose'?: boolean;
    'dry_run'?: boolean;
    'auto_approve'?: boolean;
    'preserve_sandbox'?: boolean;
    'label'?: Array<string>;
    /**
     * Raw repeated CLI input overrides, each in `KEY=VALUE` form.
     */
    'input'?: Array<string>;
}
