/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { McpTransportView } from './mcp-transport-view';

/**
 * Public server-managed MCP server definition. Transport env/header values are never returned.
 */
export interface McpServer {
    /**
     * Stable MCP server identifier, used as the runtime MCP server name in qualified tool names.
     */
    'id': string;
    /**
     * Stable revision used with `If-Match` for optimistic concurrency.
     */
    'revision': string;
    /**
     * Human-readable label for display in management UIs.
     */
    'display_name': string;
    'description': string | null;
    'transport': McpTransportView;
    /**
     * Seconds to wait for the MCP server to become ready at connect time.
     */
    'startup_timeout_secs': number;
    /**
     * Seconds to allow each MCP tool call before timing out.
     */
    'tool_timeout_secs': number;
}
