/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { McpHttpProtocol } from './mcp-http-protocol';
// May contain unused imports in some cases
// @ts-ignore
import type { McpTransportViewHttp } from './mcp-transport-view-http';
// May contain unused imports in some cases
// @ts-ignore
import type { McpTransportViewSandbox } from './mcp-transport-view-sandbox';
// May contain unused imports in some cases
// @ts-ignore
import type { McpTransportViewStdio } from './mcp-transport-view-stdio';

/**
 * @type McpTransportView
 * MCP server transport configuration returned by catalog read APIs.
 */
export type McpTransportView = { type: 'http' } & McpTransportViewHttp | { type: 'sandbox' } & McpTransportViewSandbox | { type: 'stdio' } & McpTransportViewStdio;
