/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Stdio transport view. Environment variable values are omitted.
 */
export interface McpTransportViewStdio {
    'type': McpTransportViewStdioTypeEnum;
    /**
     * Command and arguments used to launch the MCP server.
     */
    'command': Array<string>;
    /**
     * Environment variable names configured for this transport.
     */
    'env_keys': Array<string>;
}

export const McpTransportViewStdioTypeEnum = {
    STDIO: 'stdio'
} as const;

export type McpTransportViewStdioTypeEnum = typeof McpTransportViewStdioTypeEnum[keyof typeof McpTransportViewStdioTypeEnum];
