/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { McpHttpProtocol } from './mcp-http-protocol';

/**
 * HTTP transport view. Header values are omitted.
 */
export interface McpTransportViewHttp {
    'type': McpTransportViewHttpTypeEnum;
    'protocol'?: McpHttpProtocol;
    'url': string;
    /**
     * HTTP header names configured for this transport.
     */
    'header_keys': Array<string>;
}

export const McpTransportViewHttpTypeEnum = {
    HTTP: 'http'
} as const;

export type McpTransportViewHttpTypeEnum = typeof McpTransportViewHttpTypeEnum[keyof typeof McpTransportViewHttpTypeEnum];
