/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Wire protocol used by HTTP and sandbox MCP transports.
 */

export const McpHttpProtocol = {
    STREAMABLE_HTTP: 'streamable_http',
    SSE: 'sse'
} as const;

export type McpHttpProtocol = typeof McpHttpProtocol[keyof typeof McpHttpProtocol];
