/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { McpHttpProtocol } from './mcp-http-protocol';

/**
 * HTTP transport that connects to a remote MCP server URL.
 */
export interface McpTransportHttp {
    'type': McpTransportHttpTypeEnum;
    'protocol'?: McpHttpProtocol;
    'url': string;
    'headers': { [key: string]: string; };
}

export const McpTransportHttpTypeEnum = {
    HTTP: 'http'
} as const;

export type McpTransportHttpTypeEnum = typeof McpTransportHttpTypeEnum[keyof typeof McpTransportHttpTypeEnum];
