/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { McpHttpProtocol } from './mcp-http-protocol';

/**
 * Sandbox transport view. Environment variable values are omitted.
 */
export interface McpTransportViewSandbox {
    'type': McpTransportViewSandboxTypeEnum;
    'protocol'?: McpHttpProtocol;
    /**
     * Command and arguments used to launch the in-sandbox MCP server.
     */
    'command': Array<string>;
    'port': number;
    /**
     * Environment variable names configured for this transport.
     */
    'env_keys': Array<string>;
}

export const McpTransportViewSandboxTypeEnum = {
    SANDBOX: 'sandbox'
} as const;

export type McpTransportViewSandboxTypeEnum = typeof McpTransportViewSandboxTypeEnum[keyof typeof McpTransportViewSandboxTypeEnum];
