/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Stdio transport that launches a local MCP server subprocess.
 */
export interface McpTransportStdio {
    'type': McpTransportStdioTypeEnum;
    /**
     * Command and arguments used to launch the MCP server.
     */
    'command': Array<string>;
    'env': { [key: string]: string; };
}

export const McpTransportStdioTypeEnum = {
    STDIO: 'stdio'
} as const;

export type McpTransportStdioTypeEnum = typeof McpTransportStdioTypeEnum[keyof typeof McpTransportStdioTypeEnum];
