/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ReasoningEffortFeature } from './reasoning-effort-feature';

/**
 * Capability flags for a model.
 */
export interface ModelFeatures {
    /**
     * Whether the model supports tool use.
     */
    'tools': boolean;
    /**
     * Whether the model supports vision/image inputs.
     */
    'vision': boolean;
    /**
     * Whether the model supports extended reasoning.
     */
    'reasoning': boolean;
    'reasoning_effort': ReasoningEffortFeature;
    /**
     * Whether the model endpoint supports prompt caching.
     */
    'prompt_cache': boolean;
    /**
     * Whether the endpoint only caches when the request marks the cacheable prefix with Anthropic-style cache_control breakpoints (e.g. Claude via OpenRouter).
     */
    'cache_control_breakpoints': boolean;
    /**
     * Whether the model accepts classic sampling parameters (temperature, top_p).
     */
    'sampling_params': boolean;
}
