/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ReviewTargetKind } from './review-target-kind';

/**
 * A validated external resource presented as the primary subject of a human review question.
 */
export interface ReviewTarget {
    /**
     * Human-readable link label.
     */
    'label': string;
    /**
     * Absolute HTTP or HTTPS URL opened by the reviewer.
     */
    'url': string;
    'kind': ReviewTargetKind;
}
