/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Run-level default values for typed model controls. Node and style attributes still win over these defaults.
 */
export interface RunModelControls {
    'reasoning_effort': string | null;
    'speed': string | null;
}
