/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArtifactsSettings } from './artifacts-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { HookDefinition } from './hook-definition';
// May contain unused imports in some cases
// @ts-ignore
import type { NotificationRouteSettings } from './notification-route-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestSettings } from './pull-request-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { RunAgentSettings } from './run-agent-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { RunBranchSettings } from './run-branch-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { RunCheckpointSettings } from './run-checkpoint-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { RunCloneSettings } from './run-clone-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { RunEnvironmentSettings } from './run-environment-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { RunExecutionSettings } from './run-execution-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { RunGitSettings } from './run-git-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { RunGoal } from './run-goal';
// May contain unused imports in some cases
// @ts-ignore
import type { RunIntegrationsSettings } from './run-integrations-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { RunInterviewsSettings } from './run-interviews-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { RunMetaBranchSettings } from './run-meta-branch-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { RunModelSettings } from './run-model-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { RunPrepareSettings } from './run-prepare-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { RunScmSettings } from './run-scm-settings';

export interface RunNamespace {
    'goal': RunGoal | null;
    /**
     * Config string that can contain typed interpolation tokens.
     */
    'working_dir': string | null;
    'metadata': { [key: string]: string; };
    'inputs': { [key: string]: any; };
    'model': RunModelSettings;
    'git': RunGitSettings;
    'prepare': RunPrepareSettings;
    'execution': RunExecutionSettings;
    'checkpoint': RunCheckpointSettings;
    'clone': RunCloneSettings;
    'run_branch': RunBranchSettings;
    'meta_branch': RunMetaBranchSettings;
    'environment': RunEnvironmentSettings;
    'notifications': { [key: string]: NotificationRouteSettings; };
    'interviews': RunInterviewsSettings;
    'agent': RunAgentSettings;
    'hooks': Array<HookDefinition>;
    'scm': RunScmSettings;
    'pull_request': PullRequestSettings | null;
    'artifacts': ArtifactsSettings;
    'integrations': RunIntegrationsSettings;
}
