/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ForkSourceRef } from './fork-source-ref';
// May contain unused imports in some cases
// @ts-ignore
import type { GitContext } from './git-context';
// May contain unused imports in some cases
// @ts-ignore
import type { RunProvenance } from './run-provenance';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowSettings } from './workflow-settings';

/**
 * Durable workflow run specification reconstructed from run.created events.
 */
export interface RunSpec {
    'run_id': string;
    'settings': WorkflowSettings;
    'graph': { [key: string]: any; };
    'graph_source'?: string | null;
    'workflow_slug'?: string | null;
    'source_directory'?: string | null;
    'labels'?: { [key: string]: string; };
    'provenance': RunProvenance;
    'manifest_blob'?: string | null;
    'definition_blob'?: string | null;
    'git'?: GitContext | null;
    'fork_source_ref'?: ForkSourceRef | null;
}
