/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RunGoalFile {
    'type': RunGoalFileTypeEnum;
    /**
     * Config string that can contain typed interpolation tokens.
     */
    'value': string;
}

export const RunGoalFileTypeEnum = {
    FILE: 'file'
} as const;

export type RunGoalFileTypeEnum = typeof RunGoalFileTypeEnum[keyof typeof RunGoalFileTypeEnum];
