/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Principal } from './principal';

/**
 * Internal RunEvent-compatible JSON payload. The server validates this body by deserializing into the typed RunEvent struct.
 */
export interface RunEvent {
    [key: string]: any;

    'id': string;
    'ts': string;
    'run_id': string;
    'node_id'?: string | null;
    'node_label'?: string | null;
    /**
     * Stage execution identity, formatted as \"{node_id}@{visit}\".
     */
    'stage_id'?: string | null;
    /**
     * Durable identity of one execution of a parallel node, formatted as \"{node_id}@{visit}\".
     */
    'parallel_group_id'?: string | null;
    /**
     * Durable identity of one branch within a parallel execution, in `{parallel_group_id}:{index}` form.
     */
    'parallel_branch_id'?: string | null;
    'session_id'?: string | null;
    'parent_session_id'?: string | null;
    /**
     * Stable identifier for a tool call, present on agent.tool.* events and other durable events that directly describe the same tool call.
     */
    'tool_call_id'?: string | null;
    'actor'?: Principal | null;
    /**
     * Event type discriminator.
     */
    'event': string;
    'properties'?: { [key: string]: any; };
}
