/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ServerDockerWorkerSettings {
    'image': string | null;
    'server_url': string | null;
    'network': string | null;
    'docker_socket': string | null;
    'remove_on_exit': boolean;
}
