/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ServerApiSettings } from './server-api-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ServerArtifactsSettings } from './server-artifacts-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ServerAuthSettings } from './server-auth-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ServerIntegrationsSettings } from './server-integrations-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ServerListenSettings } from './server-listen-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ServerLoggingSettings } from './server-logging-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ServerSandboxSettings } from './server-sandbox-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ServerSchedulerSettings } from './server-scheduler-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ServerSlateDbSettings } from './server-slate-db-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ServerStorageSettings } from './server-storage-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ServerWebSettings } from './server-web-settings';
// May contain unused imports in some cases
// @ts-ignore
import type { ServerWorkerSettings } from './server-worker-settings';

export interface ServerNamespace {
    'listen': ServerListenSettings;
    'api': ServerApiSettings;
    'web': ServerWebSettings;
    'auth': ServerAuthSettings;
    'sandbox': ServerSandboxSettings;
    'worker': ServerWorkerSettings;
    'storage': ServerStorageSettings;
    'artifacts': ServerArtifactsSettings;
    'slatedb': ServerSlateDbSettings;
    'scheduler': ServerSchedulerSettings;
    'logging': ServerLoggingSettings;
    'integrations': ServerIntegrationsSettings;
}
