/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * One open tool batch: tool calls dispatched together that have not all reported completion. `open_call_ids` is a set rather than a count so a duplicated completion in a replayed log cannot drain the batch early.
 */
export interface StageToolBatchProjection {
    /**
     * Root agent session that dispatched the batch. Transitions are gated on it so delayed events from a replaced session cannot mutate the current batch.
     */
    'session_id': string;
    /**
     * When the batch opened — the first dispatched call observed while no other calls were outstanding.
     */
    'started_at': string;
    /**
     * Calls dispatched but not yet completed, by tool call id.
     */
    'open_call_ids': Array<string>;
}
