/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Tool surface a todo list belongs to. Determines the `list_id` prefix and scoping convention.
 */

export const TodoListKind = {
    OPENAI_PLAN: 'openai_plan',
    ANTHROPIC_TASKS: 'anthropic_tasks',
    KIMI_TODOS: 'kimi_todos'
} as const;

export type TodoListKind = typeof TodoListKind[keyof typeof TodoListKind];
